---
- name: Install JVM
  become: true
  package:
    name: openjdk-11-jdk
    state: present
    update_cache: true

- name: Set kafka download variables
  set_fact:
    kafka_download_url: "http://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    kafka_download_dest: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"

- name: Download kafka package
  get_url:
    url: "{{ kafka_download_url }}"
    dest: "{{ kafka_download_dest }}"
  notify: restart kafka

- name: Extract kafka package
  become: true
  unarchive:
    src: "{{ kafka_download_dest }}"
    dest: "{{ kafka_home | dirname }}"
    mode: 0755
    remote_src: true

- name: Create symbolic link
  become: true
  file:
    src: "{{ kafka_home }}_{{ scala_version }}-{{ kafka_version }}"
    dest: "{{ kafka_home }}"
    state: link
...