kafka_version: "3.4.0"
scala_version: "2.13"

kafka_home: "/opt/kafka"
kafka_config_file: "{{ kafka_home }}/config/kraft/custom-server.properties"
kafka_log_dir: "/tmp/kraft-combined-logs"
kafka_roles:
  - broker
  - controller

kafka_service_unit_overrides:

kafka_service_overrides:
  ExecStart: "{{ kafka_home }}/bin/kafka-server-start.sh {{ kafka_config_file }}"
  ExecStop: "{{ kafka_home }}/bin/kafka-server-stop.sh"

kafka_service_environment_overrides:
  KAFKA_HEAP_OPTS: "-Xms512m -Xmx512m"
  