- name: Show return value of stat module
  hosts: vm1
  gather_facts: true
  become: true
  vars:
    stat_key: mode
  tasks:
    - name: Determine file properties
      stat:
        path: /etc/ssh/sshd_config
      register: result

    - debug: var=result

    - name: Display result.stat detail
      debug: var=result.stat[stat_key]