- name: Copy Facts
  hosts: vm1
  become: true
  gather_facts: false
  tasks:
    - name: Ensure facts.d exists
      file:
        path: /etc/ansible/facts.d/
        state: directory
        mode: 0755

    - name: Copy example fact
      copy:
        src: example.fact
        dest: /etc/ansible/facts.d/
        mode: 0644

- name: Print local facts
  hosts: vm1
  tasks:
    - name: Print ansible_local
      debug: var=ansible_local

    - name: Print book title
      debug:
        msg: "The title of the book is {{ ansible_local.example.book.title }}"